/**
 * Mapping of dog breeds to their typical size categories
 * Used for automatic size selection in booking form
 */

type SizeCategory = 'small' | 'medium' | 'large';

export const BREED_SIZES: Record<string, SizeCategory> = {
  // Small breeds
  'Affenpinscher': 'small',
  'Australian Terrier': 'small',
  'Basenji': 'small',
  'Bedlington Terrier': 'small',
  'Bichon Frise': 'small',
  'Border Terrier': 'small',
  'Boston Terrier': 'small',
  'Brussels Griffon': 'small',
  'Cairn Terrier': 'small',
  'Cavalier King Charles Spaniel': 'small',
  'Cavapoo': 'small',
  'Chihuahua': 'small',
  'Chinese Crested': 'small',
  'Chiweenie': 'small',
  'Chorkie': 'small',
  'Cockalier': 'small',
  'Coton de Tulear': 'small',
  'Dachshund': 'small',
  'English Toy Spaniel': 'small',
  'French Bulldog': 'small',
  'Frenchton': 'small',
  'Frug': 'small',
  'Havanese': 'small',
  'Italian Greyhound': 'small',
  'Jack Russell Terrier': 'small',
  'Jackapoo': 'small',
  'Japanese Chin': 'small',
  'Jug': 'small',
  'Lakeland Terrier': 'small',
  'Lhasa Apso': 'small',
  'Löwchen': 'small',
  'Maltese': 'small',
  'Maltipoo': 'small',
  'Manchester Terrier': 'small',
  'Miniature Pinscher': 'small',
  'Miniature Schnauzer': 'small',
  'Norfolk Terrier': 'small',
  'Norwich Terrier': 'small',
  'Papillon': 'small',
  'Parson Russell Terrier': 'small',
  'Pekingese': 'small',
  'Pomeranian': 'small',
  'Pomsky': 'small',
  'Poodle (Miniature)': 'small',
  'Poodle (Toy)': 'small',
  'Pug': 'small',
  'Puggle': 'small',
  'Rat Terrier': 'small',
  'Russian Toy': 'small',
  'Schipperke': 'small',
  'Scottish Terrier': 'small',
  'Sealyham Terrier': 'small',
  'Shiba Inu': 'small',
  'Shih Tzu': 'small',
  'Silky Terrier': 'small',
  'Skye Terrier': 'small',
  'Smooth Fox Terrier': 'small',
  'Swedish Vallhund': 'small',
  'Tibetan Spaniel': 'small',
  'Tibetan Terrier': 'small',
  'Toy Fox Terrier': 'small',
  'Welsh Terrier': 'small',
  'West Highland White Terrier': 'small',
  'Wire Fox Terrier': 'small',
  'Xoloitzcuintli': 'small',
  'Yorkshire Terrier': 'small',
  'Yorkipoo': 'small',

  // Medium breeds
  'Afghan Hound': 'medium',
  'Airedale Terrier': 'medium',
  'American Bulldog': 'medium',
  'American Eskimo Dog': 'medium',
  'American Staffordshire Terrier': 'medium',
  'Australian Cattle Dog': 'medium',
  'Australian Shepherd': 'medium',
  'Aussiedoodle': 'medium',
  'Basset Hound': 'medium',
  'Beagle': 'medium',
  'Bearded Collie': 'medium',
  'Belgian Malinois': 'medium',
  'Belgian Tervuren': 'medium',
  'Border Collie': 'medium',
  'Borderpoo': 'medium',
  'Borzoi': 'medium',
  'Bouvier des Flandres': 'medium',
  'Boxer': 'medium',
  'Boxador': 'medium',
  'Briard': 'medium',
  'Brittany': 'medium',
  'Bull Terrier': 'medium',
  'Bulldog': 'medium',
  'Bullmatian': 'medium',
  'Cardigan Welsh Corgi': 'medium',
  'Chow Chow': 'medium',
  'Clumber Spaniel': 'medium',
  'Cocker Spaniel': 'medium',
  'Cockapoo': 'medium',
  'Collie': 'medium',
  'Coonhound': 'medium',
  'Corgi (Cardigan Welsh)': 'medium',
  'Corgi (Pembroke Welsh)': 'medium',
  'Dalmatian': 'medium',
  'Doberman Pinscher': 'medium',
  'English Setter': 'medium',
  'English Springer Spaniel': 'medium',
  'Field Spaniel': 'medium',
  'Finnish Spitz': 'medium',
  'Flat-Coated Retriever': 'medium',
  'German Pinscher': 'medium',
  'German Shorthaired Pointer': 'medium',
  'German Wirehaired Pointer': 'medium',
  'Goberian': 'medium',
  'Goldador': 'medium',
  'Gordon Setter': 'medium',
  'Ibizan Hound': 'medium',
  'Irish Setter': 'medium',
  'Irish Terrier': 'medium',
  'Irish Water Spaniel': 'medium',
  'Keeshond': 'medium',
  'Kerry Blue Terrier': 'medium',
  'Labrabull': 'medium',
  'Labsky': 'medium',
  'Nova Scotia Duck Tolling Retriever': 'medium',
  'Old English Sheepdog': 'medium',
  'Pharaoh Hound': 'medium',
  'Plott Hound': 'medium',
  'Pointer': 'medium',
  'Poodle (Standard)': 'medium',
  'Portuguese Water Dog': 'medium',
  'Puli': 'medium',
  'Pyrenean Shepherd': 'medium',
  'Redbone Coonhound': 'medium',
  'Rhodesian Ridgeback': 'medium',
  'Saluki': 'medium',
  'Samoyed': 'medium',
  'Schnoodle': 'medium',
  'Scottish Deerhound': 'medium',
  'Shetland Sheepdog': 'medium',
  'Siberian Husky': 'medium',
  'Soft Coated Wheaten Terrier': 'medium',
  'Spanish Water Dog': 'medium',
  'Spinone Italiano': 'medium',
  'Staffordshire Bull Terrier': 'medium',
  'Standard Schnauzer': 'medium',
  'Sussex Spaniel': 'medium',
  'Vizsla': 'medium',
  'Weimaraner': 'medium',
  'Welsh Springer Spaniel': 'medium',
  'Whippet': 'medium',
  'Wirehaired Pointing Griffon': 'medium',

  // Large breeds
  'Akita': 'large',
  'Alaskan Malamute': 'large',
  'Bernedoodle': 'large',
  'Bernese Mountain Dog': 'large',
  'Bloodhound': 'large',
  'Bullmastiff': 'large',
  'Bullweiler': 'large',
  'Dogue de Bordeaux': 'large',
  'German Shepherd': 'large',
  'Giant Schnauzer': 'large',
  'Golden Retriever': 'large',
  'Goldendoodle': 'large',
  'Great Dane': 'large',
  'Great Pyrenees': 'large',
  'Greater Swiss Mountain Dog': 'large',
  'Greyhound': 'large',
  'Irish Wolfhound': 'large',
  'Komondor': 'large',
  'Kuvasz': 'large',
  'Labradoodle': 'large',
  'Labrador Retriever': 'large',
  'Leonberger': 'large',
  'Mastiff': 'large',
  'Neapolitan Mastiff': 'large',
  'Newfoundland': 'large',
  'Norwegian Elkhound': 'large',
  'Rottweiler': 'large',
  'Saint Bernard': 'large',
  'Shepador': 'large',
  'Tibetan Mastiff': 'large',
};

/**
 * Get size category for a breed
 * Returns 'medium' as default if breed not found
 */
export function getSizeForBreed(breed: string): SizeCategory {
  return BREED_SIZES[breed] || 'medium';
}
